import { GetStaticProps } from "next";
import { getDocs, collection } from "firebase/firestore";
import { db } from "@/services/firebaseConnection";
import Head from "next/head";
import Image from "next/image";
import styles from ".styles/home.module.css"
import heroImg from "../../public/assets/hero.png";

interface HomeProps {
  comments: number,
  tasks: number
}

export default function Home({ comments, tasks }: HomeProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tarefas+ | Organize suas tarefas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <div className={styles.logoContent}>
          <Image className={styles.hero} alt="logoTarefas+" src={heroImg} priority />
        </div>
        <h1 className={styles.title}>Sistema feito para você organizar <br /> seus estudos e suas tarefas</h1>
        <div className={styles.infoContent}>
          <section className={styles.box}>
            <span>+{tasks} posts</span>
          </section>
          <section className={styles.box}>
            <span>+{comments} comentários</span>
          </section>
        </div>
      </main>
      <footer className={styles.footer}>
        <div className={styles.footerContent}>
          <p className={styles.footerText}>Desenvolvido por <a href="https://github.com/DevBrigante" target="_blank" rel="noreferrer">©Brenno Brigante</a></p>
        </div>
      </footer>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const commentsRef = collection(db, "comments");
  const tasksRef = collection(db, "tasks");

  const commentsSnapshot = await getDocs(commentsRef);
  const tasksSnapshot = await getDocs(tasksRef);

  return {
    props: {
      comments: commentsSnapshot.size || 0,
      tasks: tasksSnapshot.size || 0
    },
    revalidate: 60
  }
}
